Fix: Exception when string identifier `%` (#379)
> Error: toText(...)(...) is not a function

-> Exception in `ts2fable.Name.capitalize` when input starts with `%`
Usually something like
```typescript
export type Operator =
  "==" | ... | "%" | ... | "%=" | ...;
```
(happens in packages `estree` & `babel-types`)

Error in Fable: https://github.com/fable-compiler/Fable/issues/2398
Fix until resolved: use string addition instead of formatter

Add some `capitalize` tests including `%` tests